name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        name: Deploy frontend
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "punktomat"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: "frontend"
      - uses: akhileshns/heroku-deploy@v3.8.9
        name: Deploy backend
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "punktomat-api"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: "backend"
